# Generated by Django 4.1.4 on 2023-01-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWN', 'Owner'), ('ADM', 'Admin'), ('DIS', 'Dispatcher'), ('UPD', 'Updater'), ('DRI', 'Driver')], max_length=3),
        ),
    ]
