# Generated by Django 4.0.4 on 2022-08-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_driver_app_version_driver_cdl_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='app_version',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='co_driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.driver'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='company_user_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='notes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
