# Generated by Django 4.1.4 on 2022-12-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='company',
        ),
    ]
