# Generated by Django 4.1.4 on 2023-01-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'OFF'), ('SB', 'SB'), ('DR', 'DR'), ('ON', 'ON'), ('YM', 'YM'), ('PC', 'PC'), ('LIN', 'LOGIN'), ('LOU', 'LOGOUT'), ('POF', 'POWER OFF'), ('PON', 'POWER ON'), ('CER', 'CERTIFY'), ('INT', 'INTERMEDIATE')], default='OFF', max_length=3)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('eng_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('notes', models.CharField(blank=True, max_length=20, null=True)),
                ('document', models.CharField(blank=True, max_length=20, null=True)),
                ('trailer', models.CharField(blank=True, max_length=20, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
        ),
    ]
