# Generated by Django 4.0.4 on 2022-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_driver_app_version_alter_driver_co_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
