# Generated by Django 4.1.4 on 2023-01-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_elduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='company_user_id',
        ),
    ]
