# Generated by Django 4.1.4 on 2023-01-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='elduser',
            name='activate_driver_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='create_driver_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='update_driver_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='view_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='view_driver_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='view_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='view_vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
