# Generated by Django 4.1 on 2022-08-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_log_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='loc_name',
            new_name='location',
        ),
    ]
