# Generated by Django 4.1.4 on 2023-01-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_driver_company_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(choices=[('Y99', '1999'), ('Y00', '2000'), ('Y01', '2001'), ('Y02', '2002'), ('Y03', '2003'), ('Y04', '2004'), ('Y05', '2005'), ('Y06', '2006'), ('Y07', '2007'), ('Y08', '2008'), ('Y09', '2009'), ('Y10', '2010'), ('Y11', '2011'), ('Y12', '2012'), ('Y13', '2013'), ('Y14', '2014'), ('Y15', '2015'), ('Y16', '2016'), ('Y17', '2017'), ('Y18', '2018'), ('Y19', '2019'), ('Y20', '2020'), ('Y21', '2021'), ('Y22', '2022'), ('Y23', '2023'), ('Y24', '2024'), ('Y24', '2025'), ('Y24', '2026')], default='23', max_length=3),
        ),
    ]
