# Generated by Django 4.1 on 2022-08-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_log_document_alter_log_eng_hours_alter_log_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
