# Generated by Django 4.0.4 on 2022-08-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vehicle_eld_device_alter_vehicle_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
