# Generated by Django 4.1.1 on 2022-09-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_log_lat_alter_log_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('OFF', 'OFF'), ('SB', 'SB'), ('DR', 'DR'), ('ON', 'ON'), ('YM', 'YM'), ('PC', 'PC'), ('LIN', 'LOGIN'), ('LOU', 'LOGOUT'), ('POF', 'POWER OFF'), ('PON', 'POWER ON'), ('CER', 'CERTIFY'), ('INT', 'INTERMEDIATE')], default='OFF', max_length=3),
        ),
    ]
