# Generated by Django 4.1.4 on 2023-01-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_driver_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elduser',
            old_name='create_new_user',
            new_name='activate_driver',
        ),
        migrations.AddField(
            model_name='elduser',
            name='activate_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='create_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='create_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='update_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='update_user',
            field=models.BooleanField(default=False),
        ),
    ]
