# Generated by Django 4.0.4 on 2022-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_driver_cdl_number_alter_driver_cdl_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
