# Generated by Django 4.0.4 on 2022-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_driver_notes_alter_driver_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
