# Generated by Django 4.1.4 on 2023-01-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_elduser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='elduser',
            name='activate_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='create_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elduser',
            name='update_vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
